version: '3'
services:
  api:
    image: trello-express-app
    build: .
    networks:
      - backend
    ports:
      - "5000:5000"

  web-cli:
    image: trello-express-app
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge